### ISSUE TITLE
Some of attributes of chat.list are returning undefined 

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2491]
### WA-JS Version

3.14.2-alpha.0

### WhatsApp Version

2.3000.1018197845

### Browser Version

Chrome 130

### Operation System

Window 11

### Steps to reproduce

```
let a  = WPP.whatsapp.ChatStore._models;
undefined
a[0].kind
undefined
a[0].isUser
undefined
a[0].isPSA
undefined
a[0].isParentGroup
undefined
a[0].shouldAppearInList
undefined
a[0].previewMessage
undefined
a[0].showChangeNumberNotification
undefined
a[0].shouldShowUnreadInTitle
undefined
```

![image](https://github.com/user-attachments/assets/b0a04f17-559b-455a-abff-6dd9f9095455)

### What is expected?

return proper output

### What is actually happening?

undefined

**Comment by kakaPup** [comment]
I have the same problem, please help.

**Comment by matias-carpintini** [comment]
has anyone figured it out?

**Comment by matias-carpintini** [comment]
@bracketsApps007 have you found something?

**Comment by dllsystem** [comment]
same problem here

**Comment by matias-carpintini** [comment]
@icleitoncosta i still can't filter chats with that patch. any ideas?

**Comment by icleitoncosta** [comment]
> @icleitoncosta i still can't filter chats with that patch. any ideas?
What is the function you are calling?

**Comment by matias-carpintini** [comment]
@icleitoncosta i'm trying this:
```
window.Store.Chat._models.forEach(function (chatModel) {
      Object.defineProperty(chatModel, "shouldAppearInList", {
        get: function () {
          return chats.includes(chatModel.id._serialized);
        },
        configurable: true,
      });
    });
    window.Store.Chat._models[0].t = window.Store.Chat._models[0].t + 1;
```

**Comment by icleitoncosta** [comment]
I've just released the corrected version; please test it out

**Comment by sagardewan** [comment]
Filtering chats is still not working with the patch for me. @icleitoncosta

**Comment by bracketsApps007** [comment]
To filter only unread messages `WPP.whatsapp.Cmd.setActiveFilter('unread')`
to filter only groups `WPP.whatsapp.Cmd.setActiveFilter('group')`
Show all `WPP.whatsapp.Cmd.setActiveFilter('')`

only working this pre defined lists.. No any way to filter custom chats

**Comment by Khushal-Batham** [comment]
@bracketsApps007 @icleitoncosta ,

I want to create a custome filters like "friends", "office colleagues", "leads", etc. How can i create one?
Is there any method in WPP from which I can create a custome filters?

**Comment by marcelo386** [comment]
![image](https://github.com/user-attachments/assets/65ff0d89-ca64-4ee3-8d9c-b34dd17ebdcc)

WPP.chat.list({onlyUsers:true, onlyWithUnreadMessage: true});

onlyWithUnreadMessage not working

**Comment by erSurajMahajan** [comment]
> To filter only unread messages `WPP.whatsapp.Cmd.setActiveFilter('unread')` to filter only groups `WPP.whatsapp.Cmd.setActiveFilter('group')` Show all `WPP.whatsapp.Cmd.setActiveFilter('')`
> 
> only working this pre defined lists.. No any way to filter custom chats

filter chats using pre-defined SearchFilters

`WPP.whatsapp.Cmd.setActiveFilter('assigned_to_you')`
`WPP.whatsapp.Cmd.setActiveFilter('broadcast')`
`WPP.whatsapp.Cmd.setActiveFilter('business')`
`WPP.whatsapp.Cmd.setActiveFilter('contact')`
`WPP.whatsapp.Cmd.setActiveFilter('favorites')`
`WPP.whatsapp.Cmd.setActiveFilter('group')`
`WPP.whatsapp.Cmd.setActiveFilter('non_contact')`
`WPP.whatsapp.Cmd.setActiveFilter('personal')`
`WPP.whatsapp.Cmd.setActiveFilter('unread')`

**Comment by icleitoncosta** [comment]
> ![image](https://private-user-images.githubusercontent.com/69150213/386814891-65ff0d89-ca64-4ee3-8d9c-b34dd17ebdcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzA5OTgsIm5iZiI6MTczMTc3MDY5OCwicGF0aCI6Ii82OTE1MDIxMy8zODY4MTQ4OTEtNjVmZjBkODktY2E2NC00ZWUzLThkOWMtYjM0ZGQxN2ViZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDE1MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhN2Q0NDIwYTM1MzNkM2Q0YjY1Y2E3OGQ3NTdiZGRmZjVkZjNhODQ2MjQ0MWU0NjA0NzM0YjgzYmQ2NjY1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xF4Tb5QarFeWH-nXldlNRW8qZjoxPD6KC2t-SIzFh7c)
> 
> WPP.chat.list({onlyUsers:true, onlyWithUnreadMessage: true});
> 
> onlyWithUnreadMessage not working

Fixed by https://github.com/wppconnect-team/wa-js/commit/3d3aff295adeea46d6657fbc805f655d622bebc8

**Comment by icleitoncosta** [comment]
> Filtering chats is still not working with the patch for me. @icleitoncosta

How are you filtering the chats?
