### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by octavio1243** [wppconnect-team/wa-js#3074]
### WA-JS Version

v3.18.9-alpha.0

### WhatsApp Version

2.3000.1030318976

### Browser Version

Edge 142.0.3595.94

### Operation System

Windows 11

### Steps to reproduce

RangeError: Maximum call stack size exceeded
    at t.get (injectScript.bundle.js:255463:129643)
    at getIsWAContact (injectScript.bundle.js:255463:190)
    at t.get (injectScript.bundle.js:255463:129650)
    at getIsWAContact (injectScript.bundle.js:255463:190)
    at t.get (injectScript.bundle.js:255463:129650)
    at getIsWAContact (injectScript.bundle.js:255463:190)
    ...
    (repetición indefinida)

### What is expected?

Infinite recursion is triggered in several functions of that object: getIsUser, getIsMe, getIsGroup

### What is actually happening?

An infinite recursive call occurs

**Comment by JorsisDev** [comment]
Same whatapp update

**Comment by 4nubis0s** [comment]
Same problem here too

**Comment by mqStart** [comment]
Same issue.

**Comment by smukideejeah** [comment]
Look at the PR: https://github.com/wppconnect-team/wa-js/pull/3076

**Comment by fancywhat** [comment]
Same problem here too

**Comment by manfe** [comment]
Fixed by #3078

**Comment by kakaPup** [comment]
It didn't fix the problem; I'm still getting the same error, even though I've used the latest package.

<img width="647" height="819" alt="Image" src="https://github.com/user-attachments/assets/53486250-8afd-4448-8db1-f71d1bff3e5a" />

**Comment by molvqingtai** [comment]
It seems that this change does not completely cover the method calls to isXX func.
<img width="630" height="842" alt="Image" src="https://github.com/user-attachments/assets/b0768dc6-a947-491a-a7f0-cc5764384c06" />

**Comment by manfe** [comment]
@kakaPup @molvqingtai which functions are you guys using to raise it?

**Comment by yup-ma** [comment]
.sendTextMessage function

**Comment by manfe** [comment]
whatsapp version?

**Comment by yup-ma** [comment]
Sorry tested with new update instead of npm directly, it is working .sendTextMessage is working, thanks for the effort of maintaining it.

**Comment by manfe** [comment]
Cool, just registering that it's validated:

<img width="892" height="594" alt="Image" src="https://github.com/user-attachments/assets/40c910b3-08f9-42ab-a169-1740bf1d072d" />
