### ISSUE TITLE
iOS not receiving templateButtons & List Message

### ISSUE THREAD

**Issue by ariona** [wppconnect-team/wa-js#907]
## Description
When sending templateButtons or listMessage, it does send on WA Web, but the iOS user does not receiving any message.

## Environment
- **WhatsApp version:** 2.2305.7
- **WA-JS version(s):** 2.19.0
- **Browser:** Chrome 109.0.5414.119 (Official Build) (x86_64)
- **OS:** Monterey 12.6.2
- **MultiDevice (BETA):** yes

## Steps to Reproduce
Send templateButtons message or list message to number that use iOS

**Comment by edgardmessias** [comment]
This is a known issue, but there's nothing that we can do about it.

iOS only receives if the screen is active and unlocked

**Comment by Saifallak** [comment]
Semi Fixed By https://github.com/wppconnect-team/wa-js/commit/6ec2d93b299d70db911e53cfe740d4ee494c37cc

**Comment by edgardmessias** [comment]
Closed by https://github.com/wppconnect-team/wa-js/commit/8c91d3f149409b81c9f60dbfd266658549a0c719

**Comment by ariona** [comment]
> Closed by [8c91d3f](https://github.com/wppconnect-team/wa-js/commit/8c91d3f149409b81c9f60dbfd266658549a0c719)

this is not resolved, the message only received on WhatsApp Web, but not on receiving device, tested with version '2.23.2-alpha.0'

**Comment by edgardmessias** [comment]
@ariona , are you using a business account to send? Because the Meta blocked all buttons from business acount

**Comment by ariona** [comment]
Yes i am using business WA. That's really unfortunate,
